services:
  redis:
    image: redis:latest
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data    
    command: redis-server --save 60 1 --requirepass secret123456
    networks:
      - private_network

  mongodb:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret123456
    networks:
      - private_network  
  
  mongoexpress:
    image: mongo-express
    container_name: monto_express
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - mongodb_data:/data/db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret123456
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: secret123456
    networks:
      - private_network
    depends_on:
      - mongodb
    
volumes:
  redis-data:
  mongodb_data:
    
networks:
  private_network:
    driver: bridge