services:
  redis:
    image: redis:7.2-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1 --loglevel warning --requirepass p@$$w0rd#
    networks: 
      - test-network

volumes:
  redis-data:

networks:
  test-network:
    driver: bridge